const collection: FractalSet<FillInstruction> = {
    "sierpinski-triangle": {
        name: "Sierpinski Triangle",
        max_order: 7,
        gen: {
            sides: 3,
            ratio: 1 / 2,
            shift: 0,
            outer_radius: 600 * Math.sqrt(3),
            inner_radius: [300 * Math.sqrt(3)],
            origin: [0, 150 * Math.sqrt(3)],
            generator: ["V", 0],
            keep_outer_radius: false,
        },
    },
    "sierpinski-pentagon": {
        name: "Sierpinski Pentagon",
        max_order: 5,
        gen: {
            sides: 5,
            ratio: 1 / (1 + 2 * Math.cos(Math.PI / 5)),
            shift: 0,
            outer_radius: 900 / Math.sin((2 * Math.PI) / 5),
            inner_radius: [(900 / Math.sin((2 * Math.PI) / 5)) * (1 - 1 / (1 + 2 * Math.cos(Math.PI / 5)))],
            origin: [0, ((900 / Math.sin((2 * Math.PI) / 5)) * (1 - Math.cos(Math.PI / 5))) / 2],
            generator: ["V", 0],
            keep_outer_radius: false,
        },
    },
    "sierpinski-hexagon": {
        name: "Sierpinski Hexagon",
        max_order: 5,
        gen: {
            sides: 6,
            ratio: 1 / 3,
            shift: 0,
            outer_radius: 900,
            inner_radius: [600],
            origin: [0, 0],
            generator: ["V", 0],
            keep_outer_radius: false,
        },
    },
    pentaflake: {
        name: "Pentaflake",
        max_order: 5,
        gen: {
            sides: 5,
            ratio: 1 / (1 + 2 * Math.cos(Math.PI / 5)),
            shift: 0,
            outer_radius: 900 / Math.sin((2 * Math.PI) / 5),
            inner_radius: [(900 / Math.sin((2 * Math.PI) / 5)) * (1 - 1 / (1 + 2 * Math.cos(Math.PI / 5)))],
            origin: [0, ((900 / Math.sin((2 * Math.PI) / 5)) * (1 - Math.cos(Math.PI / 5))) / 2],
            generator: ["VC", 0],
            keep_outer_radius: false,
        },
    },
    hexaflake: {
        name: "Hexaflake",
        max_order: 5,
        gen: {
            sides: 6,
            ratio: 1 / 3,
            shift: 0,
            outer_radius: 900,
            inner_radius: [600],
            origin: [0, 0],
            generator: ["VC", 0],
            keep_outer_radius: false,
        },
    },
    "hex-nut": {
        name: "Hex Nut",
        max_order: 5,
        gen: {
            sides: 6,
            ratio: 1 / 3,
            shift: 0,
            outer_radius: 900,
            inner_radius: [300 * Math.sqrt(3)],
            origin: [0, 0],
            generator: ["V", 30],
            keep_outer_radius: false,
        },
    },
    "hex-pool": {
        name: "Hex Pool",
        max_order: 5,
        gen: {
            sides: 6,
            ratio: 1 / 3,
            shift: 0,
            outer_radius: 900,
            inner_radius: [300 * Math.sqrt(3)],
            origin: [0, 0],
            generator: ["VC", 30],
            keep_outer_radius: false,
        },
    },
    "sierpinski-carpet": {
        name: "Sierpinski Carpet",
        max_order: 5,
        gen: {
            sides: 4,
            ratio: 1 / 3,
            shift: 45,
            outer_radius: 900 * Math.SQRT2,
            inner_radius: [600 * Math.SQRT2, 600],
            origin: [0, 0],
            generator: ["VS"],
            keep_outer_radius: false,
        },
    },
    "vicsek-fractal": {
        name: "Vicsek Fractal",
        max_order: 6,
        gen: {
            sides: 4,
            ratio: 1 / 3,
            shift: 45,
            outer_radius: 900 * Math.SQRT2,
            inner_radius: [600 * Math.SQRT2],
            origin: [0, 0],
            generator: ["VC", 45],
            keep_outer_radius: false,
        },
    },
    "vicsek-fractal-2": {
        name: "Vicsek Fractal 2",
        max_order: 6,
        gen: {
            sides: 4,
            ratio: 1 / 3,
            shift: 45,
            outer_radius: 900 * Math.SQRT2,
            inner_radius: [600],
            origin: [0, 0],
            generator: ["VC", 0],
            keep_outer_radius: false,
        },
    },
    "t-square": {
        name: "T Square",
        max_order: 6,
        gen: {
            sides: 4,
            ratio: 1 / 2,
            shift: 45,
            outer_radius: 900 * Math.SQRT2,
            inner_radius: [900 * Math.SQRT2],
            origin: [0, 0],
            generator: ["VC", 45],
            keep_outer_radius: true,
        },
    },
};

export default collection;
