name: Build And Deploy

on:
    push:
        branches: 
            - main
        paths-ignore:
            - "*.md"
    workflow_dispatch:

env:
    CDN_URL: ${{ vars.CDN_URL }}
    DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
                  run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm build
            - uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: "./dist"
